### ISSUE TITLE
Example of use?

### ISSUE THREAD

**Issue by milutz** [shaun4477/GvmLightControl#1]
Could you add an example of use to the Readme of this project?

I understand that you have a ESP32 using it's wifi to connect to the GVM light, but then what are you doing with the ESP32 to tell it what you want to do? Serial/USB connection between the ESP32 and a PC? User Interface directly on the ESP32? Bluetooth or wifi AP switching?

I do see some UI elements in https://github.com/shaun4477/GvmLightControl/blob/main/examples/Light_Settings_UI_for_m5/Light_Settings_UI_for_m5.ino with has some notes that it is for "m5stick-c or m5stack core" so I'm guessing https://shop.m5stack.com/collections/m5-controllers/products/m5stickc-plus-esp32-pico-mini-iot-development-kit or (maybe?) https://shop.m5stack.com/collections/m5-controllers/products/esp32-basic-core-iot-development-kit-v2-6 ?

Did you use this code for anything other than UI local to the ESP32?

**Comment by shaun4477** [comment]
Hey @milutz , that's right, the main repo is a library that you can use with basically any ESP32 board. There is an example in the examples/Light_Settings_UI_for_m5 directory that is for the m5stick-c. That device has an LCD, buttons etc, so the UI is entirely on the screen using the buttons. 

You can easily use the library on an ESP32 via Serial or something, but I haven't included any code for that. You could also do WiFi but it would be painful because you'd need to jump between networks. Bluetooth would work too, but feels like the harder road to me.

**Comment by milutz** [comment]
Awesome, thanks @shaun4477 for the the feedback (and all the work on the repo in the first place!)

My goal is to be able to control my GVM-50RS from home assistant.   (As best I can tell) the 50RS is one of the wifi-only models, with the newer models running with bluetooth.

I'm researching/waffling between trying this code with ESP32 hung off a raspberry pi and/or an ethernet connected wifi raspberry pi with the (ip only) lib at https://github.com/soekul/libgvmled

Thanks again for the quick answer!
